### ISSUE TITLE
related ximage for matrix plots

### ISSUE THREAD

**Issue by mdsumner** [grantmcdermott/tinyplot#115]
I just wanted to ping here with [ximage](https://github.com/hypertidy/ximage) - I know that extensions here won't be in scope in the near future, but I was very happy to find plot2 and see some of the inconsistencies and gaps fixed up  (`add=TRUE` [omghoddd](https://stackoverflow.com/questions/18262017/why-does-plot-not-respect-add-true) thank you!!!!).  Maybe others are looking for the same for image() as well, so please excuse the post here. 

{ximage} is probably the single best move I've ever made in R, and while it's not for everyone it consolidates a lot of gaps that live in the image()/rasterImage() zone and that are only partially addressed by a growing number of "spatial" packages that don't help my needs. 

I'll be exploring and watching the progress of plot2 and hope to provide a bit more of stance of how it might relate to ximage in future.

**Comment by grantmcdermott** [comment]
SGTM and thanks for sharing; `ximage` looks cool.

FWIW, you're right that extensions aren't currently in scope. But this package was build with (other) package developers in mind, so a goal is to make it easy to repurpose the scaffolding. One example is the [`draw_legend()`](https://grantmcdermott.com/plot2/man/draw_legend.html#examples) function, which we've exported so that others can use it more easily with their own plot methods.

**Comment by grantmcdermott** [comment]
Closing since I don't think there's anything to do right now. On a quasi-related spatial note, though: I recently added support for `type = "polygon"` if you end up playing around with spatial vector types (instead of rasters) down the toad.
