### ISSUE TITLE
License

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#119]
I personally prefer Mozilla, but GPL-3 is probably required here given use of graphics and grDevices.

**Comment by zeileis** [comment]
Usual disclaimer: I'm not a lawyer.

Nevertheless some comments after re-reading the [FSF's advice on the MPL](https://www.gnu.org/licenses/license-list.html#MPL-2.0).

- If we just call functions from graphics and grDevices, my understanding is that it would be fine to use the MPL for the package as well.

- If we copy certain snippets from graphics/grDevices then we would be obliged to use the GPL. But then we should also list the R Core Team as a contributor. I think that this is currently not necessary.

- Personally, I would prefer to keep the GPL for the package, simply because it's the most popular copyleft license in the R community.

- As usual, this is your call, though.

**Comment by grantmcdermott** [comment]
Looking at this again (and reading up on my employer's licensing stance), I now think we should just go with MIT or Apache 2.0. Both relatively common within the R community and, moreover, typically pre-approved in corporate settings too.

**Comment by zeileis** [comment]
:+1: 

I like that you chose Apache 2.0 over MIT, which is also what the FSF recommends when a permissive (non-copyleft) license should be used (https://www.gnu.org/licenses/license-list.html#apache2).
