### ISSUE TITLE
r-universe badge is broken on website

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#138]
Almost certainly related to this: https://github.com/grantmcdermott/tinyplot/issues/107#issuecomment-1930181262

I think that this requires an upstream fix to `altdoc`. Will post an issue there.

**Comment by grantmcdermott** [comment]
Tracking here: https://github.com/etiennebacher/altdoc/issues/178#issuecomment-1987339056

**Comment by vincentarelbundock** [comment]
Fixed by using `<a></a>` tag instead of markdown syntax. On the `altdoc` repo I explain why I think this is a problem with Quarto trying to be too smart. I don't think there's much to be done in `altdoc`, and the workaround here is pretty straightforward and shouldn't require manual intervention ever.

**Comment by grantmcdermott** [comment]
Great, thanks @vincentarelbundock.

(Closed by #139)
