### ISSUE TITLE
Smooth

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#144]
Would you be interested in an analogous function to `geom_smooth()`?

If so, what kind of user interface would you have in mind? How do we pass all those extra arguments?

https://ggplot2.tidyverse.org/reference/geom_smooth.html

**Comment by grantmcdermott** [comment]
Yes, definitely interested but I'm not sure about the UI side (incl. extra args).

Do you have any thoughts?

See also Achim's comment here: https://github.com/grantmcdermott/tinyplot/issues/93#issuecomment-1902802784

**Comment by zeileis** [comment]
In principle, this would be nice to have. I feel it would be important to either not introduce further arguments or to encapsulate them in such a way that they are not direct arguments of the main `tinyplot()` function.

Otherwise, if there are new arguments for the main function, it would make it harder to generalize `tinyplot()` to plots with factor variables (see https://github.com/grantmcdermott/tinyplot/issues/2) which I still haven't given up hope for.

**Comment by vincentarelbundock** [comment]
Sorry, I missed the master issue with types. Will follow up elsewhere.
