### ISSUE TITLE
Wishlist: Drawing paths

### ISSUE THREAD

**Issue by roaldarbol** [grantmcdermott/tinyplot#188]
Hi @grantmcdermott! I'm in the process of developing a couple of packages centred on animal movements. Lots of the data are paths, and I normally draw them with ggplot's `geom_path`. But for the package documentation itself, I'm looking for a more lightweight alternative - hence I'm here. 😊

So just to add to the list: It would be really great to have the ability to draw a path (as opposed to line). If it's already possible, then great! (And then you can just change this issue to be one of updating the documentation). 😉

**Comment by zeileis** [comment]
I think what you are looking for is the default behavior in base R and hence also in `tinyplot`: The plotted values are _not_ sorted by the x-variable automatically. If you want sorting, you need to do that yourself.

Let's consider a simple example data with `x` and `y` coordinates sorted by `time` within `group`.

```
d <- data.frame(
  x = c(1, 3, 1, 5, 6, 4, 5, 1),
  y = c(1, 4, 3, 3, 2, 1, 4, 2),
  time = rep(2021:2024, 2),
  group = factor(rep(c("A", "B"), each = 4))
)
```

Producing a `tinyplot` of `y` vs. `x` by `group` is essentially what `geom_path` would give you:

```
tinyplot(y ~ x | group, data = d, type = "o", col = palette.colors()[2:3], lwd = 2, pch = 19)
ggplot(d, aes(x = x, y = y, group = group, color = group)) + geom_path() + theme_bw()
```

<img src="https://github.com/user-attachments/assets/725736f8-50ea-49ba-861a-3fff7a4e62ee" width="49%" alt = "tinyplot path" />
<img src="https://github.com/user-attachments/assets/6b248e71-4133-4dcf-8d09-be79e039c60c" width="49%" alt = "tinyplot path" />

If you want the result of `geom_line()` for the same data, you would have to sort `d` by `x` first.

Or here we can take the variable `time` for illustration because it is already sorted with respect to that:

```
tinyplot(y ~ time | group, data = d, type = "o", col = palette.colors()[2:3], lwd = 2, pch = 19)
```

<img src="https://github.com/user-attachments/assets/31463cc8-3bc8-48cf-bf19-6debf92a40bb" width="49%" alt = "tinyplot sorted path" />

**Comment by roaldarbol** [comment]
That's great to know, thanks a bunch @zeileis! That can be added to the list of ggplot functions that tinyplot covers then! :-)

**Comment by grantmcdermott** [comment]
What @zeileis said ;-)

Another (albeit redundant) example would be:

```r
ggplot(iris, aes(x = Petal.Length, y = Sepal.Length, col = Species)) + geom_line()
ggplot(iris, aes(x = Petal.Length, y = Sepal.Length, col = Species)) + geom_path()
plt(Sepal.Length ~ Petal.Length | Species, iris, type = "l")
```
