### ISSUE TITLE
`tinyplot(fn(x) ~ x)` triggers inadvertent continuous groups

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#191]
First spotted by @zeileis here: https://github.com/grantmcdermott/tinyplot/pull/190#issuecomment-2267002593

Examples:

``` r
library(tinyplot)
x = 0:100/10

tinyplot(sin(x) ~ x)
```

![](https://i.imgur.com/GPBQrMU.png)

``` r
tinyplot(log(x+1) ~ x)
```

![](https://i.imgur.com/cPwCRtC.png)

``` r
tinyplot(jitter(x) ~ x)
```

![](https://i.imgur.com/X88v3ER.png)

Note that this only appears to affect the formula method. The equivalent atomic-methods plots do not produce the continuous groups:

``` r
tinyplot(x, sin(x))
```

![](https://i.imgur.com/V846Xkx.png)

``` r
tinyplot(x, log(x+1))
```

![](https://i.imgur.com/8yOqY8C.png)

``` r
tinyplot(x, jitter(x))
```

![](https://i.imgur.com/4elixhZ.png)

Similarly, it's only the case for `fn(x) ~ x`. Running `fn(y) ~ x` doesn't trigger this behaviour.

**Comment by zeileis** [comment]
Maybe we should use `format()` instead of `paste()` in `paste(attr(terms(m$formula), "variables")[[2]])` in https://github.com/grantmcdermott/tinyplot/blob/main/R/tinyplot.R#L1455

**Comment by zeileis** [comment]
Hmm, additionally, `all.vars()` does not preserve the transformation labels...will have to dig deeper.

**Comment by zeileis** [comment]
I didn't find a base R function that can extract the `term.labels` with both (a) transformations and (b) duplicates. The `term.labels` from the `terms()` preserve (a) but not (b). And `all.vars()` can preserve (b) but not (a).

Assuming that all the terms in our formulas are separated by `+` (which we used to replace `|`), the following might work:

```
all.terms = function(formula) {
  if (inherits(formula, "formula")) {
    if (length(formula) == 3L) {
      rval = deparse(formula[[2L]])
      formula = formula[[3L]]
    } else {
      rval = character(0L)
      formula = formula[[2L]]
    }
    rval <- c(rval, all.terms(formula))
  } else if (inherits(formula, "call") && formula[[1L]] == as.name("+")) {
    rval <- c(all.terms(formula[[2L]]), all.terms(formula[[3L]]))
  } else {
    rval <- deparse(formula)
  }
  return(rval)
}
```

Examples with transformations separated by `+` work correctly:

```
all.terms(y ~ x)
## [1] "y" "x"
all.terms(sin(x) ~ x)
## [1] "sin(x)" "x"     
all.terms(y ~ x + z)
## [1] "y" "x" "z"
all.terms(sin(x) ~ x + sqrt(exp(x)) + log(x))
## [1] "sin(x)"       "x"            "sqrt(exp(x))" "log(x)"      
```

I'm just not sure if we could get meaningful formulas where the terms are not separated by `+`. Or if we should throw a warning in that case because weird interpretations could occur...

**Comment by grantmcdermott** [comment]
Thanks for deep-diving here @zeileis. Your proposed solution looks elegant to me. 

> I'm just not sure if we could get meaningful formulas where the terms are not separated by +. Or if we should throw a warning in that case because weird interpretations could occur...

I might be misunderstanding here, but does this include interaction operators (`:`, `*`, `/`)?, For example, I want to ensure that we could still support formulas like the facet interaction here:

```r
plt(mpg ~ wt, mtcars, facet = ~cyl:am)
```

**Comment by zeileis** [comment]
This formula internally becomes

```
f <- mpg ~ wt + cyl:am
```

leading to this `model.frame`

```
head(model.frame(f, data = mtcars), 2)
##               mpg    wt cyl am
## Mazda RX4      21 2.620   6  1
## Mazda RX4 Wag  21 2.875   6  1
```

and these `all.vars` and `all.terms`

```
all.vars(f)
## [1] "mpg" "wt"  "cyl" "am" 
all.terms(f)
## [1] "mpg"    "wt"     "cyl:am"
```

So in this case both should results should be usable to determine whether `x` is the same as `by`. (This is the only purpose we currently need this for if I didn't overlook anything.)

But I'm not sure whether "unusual" formulas like `mpg ~ cyl | cyl:am` or `mpg ~ cyl:am | am` etc. could be processed correctly.

Or just `y ~ x | z1 - z2` which currently is interpreted like `y ~ x | z1 + z2`. Here, determining the position of `by` in the `model.frame` might not work the same as before. But we haven't got the super-safest formula processing anyway. For example, `y ~ 1 | x` is interpreted the same as `y ~ x` because there are just two variables in the `model.frame`. The question is how much work we want to spend processing stuff like this to throw informative errors. We might end up re-implementing the `Formula` package...

**Comment by grantmcdermott** [comment]
> The question is how much work we want to spend processing stuff like this to throw informative errors. We might end up re-implementing the Formula package...

Ugh, sorry. I know that my dogmatic stance on sticking to base-only is creating headaches here. On balance, I still think that this is the right stance for **tinyplot** but I'm well aware that it can create extra work.

I've got a busy week coming up, so I probably won't be able to think much more about this right now. In general though, I think that not being able to catch all of the "odd" cases is just something we might have to live with. 

I don't want to impose additional work on you @zeileis, but you are the resident formula expert so I'd defer to your opinion if you think the `all.terms` approach is the best compromise :-)

**Comment by zeileis** [comment]
I agree. For this project I think it's better to stay with the simple formula processing. I'll suggest a paragraph in the documentation about this.
