### ISSUE TITLE
Make internal: `draw_legend()` and `get_saved_par()`

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#201]
Currently, `draw_legend()` and `get_saved_par()` are both exported and documented:

http://grantmcdermott.com/tinyplot/man/draw_legend.html

Should we make them internal?

The documentation for `draw_legend()` already states that this is an internal function, so it may just be missing and `@keyword internal` tag.

I've read the `get_saved_par()` documentation a couple times, and I still can't quite figure out why it is attractive or convenient for users. In fact, the documentation itself shows how they can achieve similar results with the classic solution of:

```r
op = par(no.readonly = TRUE)  # save current par settings 
# <do lots of (tiny)plotting>
par(op)                       # reset original pars
```

I see why this function is useful internally, but I feel that the `tinyplot` spirit should also apply to NAMESPACE, and that to the extent possible, we should direct users to a base R solution.

(Obviously, this is not a big deal. I'm just reading the documentation for the first time and thinking of clean-ups and improvements.)

**Comment by grantmcdermott** [comment]
Typing quickly on my phone, so won't be able to give full details/reasoning (sorry)... But tl;dr  I think both should remain exported.

`get_saved_par` was written to comply with CRAN requests, so that has to stay. (It does more than just `par` since it captures the parameter state at different points before/after tinyplot has changed these settings.) See https://github.com/grantmcdermott/tinyplot/issues/108#issuecomment-2174642188

`draw_legend` was originally exported back in https://github.com/grantmcdermott/tinyplot/pull/94 My motivation at the time was to enable legend drawing outside of the margins&mdash;which I think is generally useful, but takes quite a bit of work&dash;for users even if they didn't want to (or couldn't) go through our main `tinyplot()` function.

**Comment by vincentarelbundock** [comment]
Sounds good.

Eventually, I'll probably go through the full documentation and recommend some changes for clarification. Maybe we can leave this issue open and I can circle back to it eventually.

**Comment by grantmcdermott** [comment]
In the spirit of the recent tidy-ups, can we close this now?
