### ISSUE TITLE
In VSCode, first plot does not appear, only after creating a second plot

### ISSUE THREAD

**Issue by strengejacke** [grantmcdermott/tinyplot#212]
## Setup

Version: 1.93.0 (system setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

R 4.4.1

## Problem

I have following code:

```r
library(tinyplot)
aq = transform(
  airquality,
  Month = factor(Month, labels = month.abb[unique(Month)])
)
aq$grp <- sample.int(3, nrow(aq), replace = TRUE)

tinyplot(
  Temp ~ Day | Month + grp,
  data = aq,
  pch = 16,
  cex = 2,
  frame = FALSE,
  grid = TRUE,
  facet.args = list(bg = "grey90")
)

tinyplot(
  y = aq$Temp,
  x = aq$Day,
  by = interaction(aq$Month, aq$grp),
  data = aq,
  pch = 16,
  cex = 2,
  frame = FALSE,
  grid = TRUE
)

tinyplot(
  Temp ~ Day | Month,
  facet = ~ grp,
  data = aq,
  pch = 16,
  cex = 2,
  frame = FALSE,
  grid = TRUE,
  facet.args = list(bg = "grey90")
)
```

When I run this code in VSCode, the first plot does not open the plot-view. After creating the second plot, the second one is shown in the plot view and both plots are accessible in the plot-history. This happens after initial start of VSCode.

Not sure if this is a _tinyplot_ issue or VSCode issue - in RStudio, everything works fine.

**Comment by grantmcdermott** [comment]
Hmmm, I can't replicate. Everything works out the gate for me in my local VS Code session.

Are you using `httpgd` or the native plot viewer?

**Comment by strengejacke** [comment]
> Edit: To help narrow down, can you also confirm that vanilla plot(1:10) doesn't produce the same behaviour? Thanks.

Yes, same behaviour. I'm using _httpgd_. Maybe it's not related to the pkg?

**Comment by strengejacke** [comment]
Interestingly, this doesn't happen with _ggplot_, where the plot immediately appears.

**Comment by strengejacke** [comment]
Results are even worse for _Positron_ (https://github.com/posit-dev/positron/issues/4611), but I guess that's likely to be a Positron issue.

**Comment by grantmcdermott** [comment]
> Yes, same behaviour. I'm using httpgd. Maybe it's not related to the pkg?

Thanks, that's helpful. In that case, I think we can rule out **tinyplot**, specifically, being the problem.

My guess is that this is a VS Code issue. I haven't upgraded to the latest release that you are using, so that may well be the problem. However, before closing and passing to an upstream source, do you mind running the following code&mdash;one line at a time&mdash;in a pure terminal environment (R console / radian / nvim.R / ESS / etc):

```
library(httpgd)
hgd()
hgd_browse()
plot(1:10)
dev.off()
```

And then trying the same thing with tinyplot:

```
library(httpgd)
hgd()
hgd_browse()
library(tinyplot)
plt(1:10)
dev.off()
```

If both of those work (like they do on my system), then I think we should probably close here and raise this issue at the [vscode-R extension](https://github.com/REditorSupport/vscode-R) repo.

**Comment by strengejacke** [comment]
Yes, both work fine. I'll close then.
