### ISSUE TITLE
Function with alternative syntax

### ISSUE THREAD

**Issue by strengejacke** [grantmcdermott/tinyplot#215]
Not sure if one of the goals is to encourage learning about base R graphics, but some of the arguments in base R don't have very intuitive names (like `pch`, `cex`, `lty`, ...), which makes the usage of base R graphics harder for beginners (and probably even people who already work since years with R, like me - I'm also struggling).

My suggestion: add a new function that simply wraps `tinyplot()`, but which only differs in their argument names.

e.g.

```r
tinyplot_2(data, dot_style = "filled", dot_size = 12)
```

which internally just calls

```r
tinyplot(data, pch = 16, cex = 3)
```

What do you think?

**Comment by vincentarelbundock** [comment]
Right. I understand the impulse and agree that some of the names are unintuitive.

But consistency with Base is one of the major benefits and key design decisions.l, and I really really don't this we should go down this rabbit hole.

Some could just write a `friendlyplot` wrapper if they want. But `tinyplot` should focus on drawing plots, not reinvent the interface.

**Comment by strengejacke** [comment]
Yeah, I didn't want to alter the initial design decision. Just an _additional_ (optional) wrapper function. But I see the point that the maintenance load would increase and out of the package's scope.

**Comment by grantmcdermott** [comment]
+1 to @vincentarelbundock's comment. I think it's scope creep that could add a non-trivial maintenance burden without super clear upside.

Two "for what it's worth"s though:

1. We do support a _few_ aliases like `fill`  for `bg`. But this is partly to ensure better consistency across different base plot types (e.g., we always use `col` instead of `border`, so `fill` seemed a natural companion to include here). 
2. I would like to include a "base/tinyplot for ggplot2 users" vignette or slidedeck at some point. Something for the backburner!

**Comment by grantmcdermott** [comment]
PS. Forgot to add: thanks for the suggestion @strengejacke. It's always great to get feedback and suggestions from engaged new users.
