### ISSUE TITLE
Should type_histogram (and co.) be exported?

### ISSUE THREAD

**Issue by grantmcdermott** [grantmcdermott/tinyplot#231]
In the NEWS, we say:

> Breaking changes:
>
> * Type-specific arguments are no longer passed through the main function via
> `...`. Instead, they are now passed through a dedicated `type_*()` functions in
> the `type` argument.

So I was a bit surprised that this didn't work:

```r
plt(
    ~Petal.Width | Species, iris,
    type = type_histogram(breaks = 30)
) 
#> Error in type_histogram(breaks = 30) : 
#>   could not find function "type_histogram"
```

Looking at the [code](https://github.com/grantmcdermott/tinyplot/blob/main/R/type_histogram.R), I can see two issues:

1) We don't actually export `type_histogram()`.
2) We don't pass arguments from this top-level function down to the companion `data_histogram()` function.

I assume that we want to do both of these things, and similarly for other non-exported types like `type_density()`. @vincentarelbundock does that sound right right to you? I just want to make sure that any changes I make are consistent with the new `types` design.

P.S. Related to #225 since background alpha is another argument that could be inherited from `type_histogram()`.

**Comment by vincentarelbundock** [comment]
Yes, that's sounds right. I didn't bother exporting type functions unless they had arguments, and `type_histogram()` does not currently have arguments.

I agree that these functions could be made more flexible and they should be exported when we make them more flexible.

Note that density is the only weird case because it is implemented as a complex and totally separate function. I never actually looked into how that all worked and was afraid of it. Ideally, I think it should also be converted to the new system, but I don't know what would be involved.

AFAICT, density is the only legacy type. All others have their own type_fun() that we can improve and export as needed.

**Comment by vincentarelbundock** [comment]
@grantmcdermott I really don't think we should be exporting both type_histogram() and type_hist().

It's one thing if you want to allow string shortcuts, but having multiple functions for the same thing just pollutes the namespace, makes it harder for users to navigate the docs, and makes IDE completion less effective.

(I also think that "hist" and "histogram" adds confusion and no efficiency, but that's still less objectionable than a full function.)

**Comment by grantmcdermott** [comment]
I hear you on namespace pollution, but my motivation here was to ensure consistency. If we support "hist" then `type_hist()` maintains the `type_<typename>` mirroring.

(I know that we discussed this separately, but I also think that supporting "hist" makes sense in the first place since we are trying to preserve the strong equivalency with base `hist`.)

That being said, I'm certainly not overly committed to this `type_hist` alias. Feel free to remove/unexport if you'd like. Or, feel free to ask @zeileis for a tie-break vote :-)

**Comment by vincentarelbundock** [comment]
TBC, this is not a big deal at all. I must have felt argumentative when I posted this ;)
