### ISSUE TITLE
`draw` should work with `add=TRUE`

### ISSUE THREAD

**Issue by vincentarelbundock** [grantmcdermott/tinyplot#247]
Currently, the `draw` evaluation is inside an `if(add=FALSE)`. This means that we cannot use the `draw` argument in `tinyplot_add()`. This would be necessary to implement `type_hline()` and friends. For example,

```r
type_hline = function(h = 0, col = "black", lty = 1, lwd = 1) {
  out = list(
    draw = function(...) invisible(NULL),
    data = data_hline(h = h, col = col, lty = lty, lwd = lwd),
    name = "hline"
  )
  class(out) = "tinyplot_type"
  return(out)
}

data_hline = function(h = 0, col = "black", lty = 1, lwd = 1) {
  fun = function(...) {
    out = list(
      draw = bquote(abline(h = .(h), col = .(col), lty = .(lty), lwd = .(lwd))),
      type = "n")
    return(out)
  }
  return(fun)
} 

plt(mpg ~ hp | factor(cyl), facet = ~ factor(cyl), data = mtcars)
plt_add(type = type_hline(h = 12))
```

_GM: Edited to say `if(add=FALSE)`_

**Comment by grantmcdermott** [comment]
Yeah, this is tricky since we (a) currently only evaluate facets if `(add=FALSE)` and (b) we need to place `draw` inside the facet logic. 

Right now my thoughts are that changing (a) would require a major overhaul of the faceting logic and I'm not even sure how it would look. For (b) we could potentially draw the elements as part of the `type_draw()` call [here](https://github.com/grantmcdermott/tinyplot/blob/6df7187c15b236026aea71f4b46f54e7ab06c874/R/tinyplot.R#L1120). But this would mean that each individual `type_*` function has to take and understand an additional `draw` argument, which would mean duplication of code and make custom types more fragile.

Another option would be to draw _after_ the `type_draw()` call, injecting facet logic where appropriate. But injecting the facet logic may be tricky in of itself and would also mean that drawn elements are placed on top of the main plotting elements, which I don't want to make the default.

I might be missing something and there could be an easier path.

OTOH, stepping back, I also wonder whether `type_hline` is inconsistent with the other types that we support? I mean, it's essentially a function-based, data-free object that doesn't have scaling in the absence of an existing plot window. 

Happy to discuss.
